version: 2.1
# Use a package of configuration called an orb.
workflows:
  # Name the workflow "welcome"
  build_test:
    jobs:
    # Run the welcome/run job in its own container
      - run:
          name: Install Python Dependencies
          command: |
            pip install -r requirements.txt
            - run:
                name: Run Test
                command: |
                  pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
            - store_test_results:
                path: test-reports
            - store_artifacts:
                path: test-reports

      - run_tests


