version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.8.11
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Test
          command: |
            python pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-containd-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests




